"""Meeting scripts for the seed. Everything is fictional. (date, hour UTC, minutes, title, host, speakers, lines, key points, decisions, actions, overall)"""

M = [
    ("2026-06-10", 7.0, 38, "North Foundry kickoff", "shah", ["zainab", "daniyal", "maya", "elena", "areeba"],
     [("shah", "Welcome everyone. Today is about how we work together and which three clients we start with."),
      ("zainab", "I have the plan: Brightpath website first, then the Harborline portal, then the Tidewell app."),
      ("daniyal", "Engineering will use two-week sprints and async standups in the engineering channel."),
      ("maya", "Each client gets a shared channel so they can ask questions without email chains."),
      ("elena", "I will run sprint planning every second Monday and send a short client update on Fridays."),
      ("areeba", "Design can start wireframes for Brightpath this week if we get the sitemap by Wednesday.")],
     ["Three launch clients: Brightpath, Harborline, Tidewell", "Two-week sprints, async standups", "One shared channel per client"],
     ["Sprints start on Mondays", "Friday client updates owned by Elena"],
     [("Elena", "Send sitemap request to Brightpath"), ("Maya", "Create shared client channels"), ("Daniyal", "Set up the repositories")],
     "The team agreed on the launch order, sprint rhythm and communication channels with clients."),
    ("2026-06-19", 8.0, 31, "Brightpath discovery review", "elena", ["elena", "maya", "areeba", "sana", "rebecca"],
     [("elena", "Thanks Rebecca for joining. We would like to confirm the sitemap and the booking flow."),
      ("rebecca", "Patients mostly book on their phones, so the booking request has to be very short."),
      ("areeba", "We can reduce it to name, phone, service and preferred time."),
      ("sana", "That also helps accessibility and keeps the form fast."),
      ("rebecca", "Perfect. We also want the team photos and a page for each service."),
      ("maya", "We will share the first wireframes in the channel by Tuesday.")],
     ["Booking form is the main conversion goal", "Service pages for implants, whitening and braces", "Team photos needed from the client"],
     ["Four fields on the booking form", "Wireframes shared by Tuesday"],
     [("Areeba", "Share homepage wireframes"), ("Rebecca", "Send team photos"), ("Sana", "Prototype the booking form")],
     "The client confirmed a short mobile-first booking form and a page for every service."),
    ("2026-07-03", 7.5, 27, "Sprint 2 review", "elena", ["elena", "daniyal", "hamza", "bilal", "areeba", "tomas"],
     [("elena", "Sprint 2 delivered visual design for Brightpath and the shipment API for Harborline."),
      ("bilal", "The shipment endpoints are on staging with pagination and filters."),
      ("tomas", "The Brightpath designs were approved on Tuesday with two colour tweaks."),
      ("hamza", "I can start the service pages as soon as the design tokens are merged."),
      ("daniyal", "Let's keep the next sprint focused on builds, not new scope.")],
     ["Brightpath designs approved", "Shipment API on staging", "Design tokens still to merge"],
     ["No new scope in sprint 3"],
     [("Hamza", "Start service pages"), ("Tomas", "Hand over final design tokens"), ("Bilal", "Document the shipment endpoints")],
     "Sprint 2 hit its goals. The team moves into build mode with no new scope."),
    ("2026-07-14", 13.0, 29, "Harborline requirements call", "maya", ["maya", "elena", "bilal", "omar", "aaron"],
     [("maya", "Aaron, we want to confirm who can see what in the portal."),
      ("aaron", "Dispatchers need everything. Customers only see their own shipments and invoices."),
      ("omar", "We can do that with customer accounts and a dispatcher role."),
      ("bilal", "Notifications by email first, SMS can follow if the budget allows."),
      ("aaron", "Email and SMS both, but SMS only for delivery day."),
      ("elena", "I will update the estimate and send it tomorrow.")],
     ["Two kinds of users: dispatchers and customers", "Email notifications for every status, SMS only on delivery day"],
     ["SMS limited to delivery day"],
     [("Elena", "Send updated estimate"), ("Omar", "Draft the role matrix"), ("Aaron", "Share a sample invoice")],
     "Roles and notification rules for the Harborline portal were settled."),
    ("2026-07-24", 8.5, 22, "Brightpath launch go/no-go", "daniyal", ["daniyal", "usman", "sana", "kamran", "elena", "rebecca"],
     [("daniyal", "Quick check before tonight's cutover. Usman, status?"),
      ("usman", "DNS is ready with a low TTL and a rollback plan written down."),
      ("kamran", "All 38 blog redirects are tested and the sitemap is ready to submit."),
      ("sana", "Accessibility pass is done and contrast issues are fixed."),
      ("rebecca", "We are happy to go ahead tonight."),
      ("daniyal", "Go. Usman owns the cutover.")],
     ["DNS and rollback ready", "Redirects verified", "Accessibility fixed"],
     ["Launch tonight, Usman owns the cutover"],
     [("Usman", "Run the DNS cutover"), ("Kamran", "Submit sitemap after launch"), ("Elena", "Message the client when live")],
     "Everything was ready and the Brightpath site was approved to go live that night."),
    ("2026-08-06", 7.0, 35, "Sales and outreach sync", "rania", ["rania", "jordan", "sofia", "zainab", "kamran"],
     [("rania", "We have sent about 1,400 emails and booked 14 calls so far."),
      ("jordan", "Clinics reply the most. Logistics companies need two follow-ups."),
      ("sofia", "I need a shorter proposal template. The current one is nine pages."),
      ("zainab", "Let's aim for three pages and a clear price table."),
      ("kamran", "I can add case study links so prospects can see the Brightpath results."),
      ("rania", "Good. Jordan will send the clinic list again next week.")],
     ["Clinics reply the most", "Logistics needs more follow-ups", "Proposal template too long"],
     ["Proposal template cut to three pages"],
     [("Sofia", "Shorten proposal template"), ("Kamran", "Add case study links to emails"), ("Jordan", "Resend the clinic list")],
     "Outreach is working best with clinics. The team will shorten proposals and add case studies."),
    ("2026-08-19", 7.0, 33, "Tidewell app design review", "areeba", ["areeba", "tomas", "hamza", "sana", "nadia"],
     [("areeba", "Nadia, here is the order flow from menu to checkout."),
      ("nadia", "I love it. Can the loyalty card sit on the home screen?"),
      ("tomas", "Yes, we can show stamps right under the greeting."),
      ("hamza", "That is easy to build and keeps the checkout short."),
      ("nadia", "Let's launch the beta in three weeks to our regulars."),
      ("sana", "We will prepare a TestFlight build before that.")],
     ["Loyalty card on the home screen", "Beta for regular customers in three weeks"],
     ["Beta target: mid September"],
     [("Tomas", "Update the home screen"), ("Sana", "Build loyalty stamps"), ("Usman", "Prepare TestFlight")],
     "The Tidewell design was approved with the loyalty card moved to the home screen."),
    ("2026-09-02", 7.5, 41, "Sprint 6 retro", "elena", ["elena", "daniyal", "hamza", "sana", "bilal", "priya", "hira", "usman"],
     [("elena", "What went well in sprint 6?"),
      ("daniyal", "Reviews were fast. Almost every PR was reviewed within a day."),
      ("hira", "QA caught the push notification bug before the client saw it."),
      ("usman", "Builds are now under three minutes after the cache change."),
      ("priya", "We underestimated the invoice PDFs. They took longer than planned."),
      ("elena", "Let's pad the estimate on anything with documents or emails.")],
     ["Reviews fast", "QA caught a notification bug early", "Builds under three minutes", "PDF work was underestimated"],
     ["Add buffer to estimates with documents or emails"],
     [("Elena", "Update the estimate checklist"), ("Hira", "Share the test plan template")],
     "A positive retro. The main lesson was to add buffer to document-heavy work."),
    ("2026-09-15", 8.0, 26, "Harborline phase 2 discussion", "sofia", ["sofia", "maya", "elena", "bilal", "aaron"],
     [("sofia", "Aaron, the pilot has been running for four weeks. How is it going?"),
      ("aaron", "Dispatchers love the tracking page. Customers ask about proof-of-delivery photos."),
      ("bilal", "We can add photo upload for drivers and show it on the shipment page."),
      ("aaron", "Great. And can we export a monthly report?"),
      ("elena", "We can scope both as phase 2 and send an estimate.")],
     ["Pilot going well", "Proof-of-delivery photos requested", "Monthly report export requested"],
     ["Scope photos and reports as phase 2"],
     [("Elena", "Send phase 2 estimate"), ("Bilal", "Spike photo upload"), ("Sofia", "Book the follow-up call")],
     "Harborline wants proof-of-delivery photos and monthly reports, both scoped as phase 2."),
    ("2026-09-22", 7.0, 36, "WebflowX product planning", "shah", ["shah", "daniyal", "hamza", "noor", "priya", "sana"],
     [("shah", "We ship fast, but first load and page switches still feel slower than they should."),
      ("hamza", "I can preload the next page and cache the workspace data on the client."),
      ("noor", "Meeting summaries are solid. The next win is turning action items into tasks."),
      ("priya", "Importers for Slack and Notion would remove the biggest switching barrier."),
      ("daniyal", "I would also publish a security page and plan single sign-on."),
      ("shah", "Order: speed first, action items to tasks second, importers third.")],
     ["Speed is priority one", "Action items to tasks is a clear product win", "Importers reduce switching cost"],
     ["Priority order: speed, action items, importers"],
     [("Hamza", "Finish preload and client cache"), ("Noor", "Prototype action items to tasks"), ("Priya", "Scope the Slack importer")],
     "The team set the WebflowX priorities for Q4: speed, action items to tasks, then importers."),
    ("2026-09-30", 8.0, 24, "Tidewell beta feedback", "hira", ["hira", "hamza", "omar", "priya", "nadia"],
     [("hira", "We had 46 testers and 31 pieces of feedback. Most are small."),
      ("nadia", "Customers want to reorder their last drink with one tap."),
      ("hamza", "That is a quick win. We can save the last order locally."),
      ("omar", "Payments worked well. We had two declined cards, both expected."),
      ("priya", "Push notifications arrive in under five seconds.")],
     ["46 testers, 31 feedback items", "Reorder last drink requested", "Payments and push notifications stable"],
     ["Add one-tap reorder before store submission"],
     [("Hamza", "Build one-tap reorder"), ("Hira", "Retest payments on iOS 17 and 18"), ("Nadia", "Invite 20 more testers")],
     "The Tidewell beta is healthy. One-tap reorder is the main addition before store submission."),
    ("2026-10-06", 7.5, 30, "Q4 planning", "zainab", ["zainab", "shah", "daniyal", "rania", "maya", "elena"],
     [("zainab", "Let's agree the Q4 targets: two new clients, one launch and a hiring plan."),
      ("rania", "The pipeline has 24 open leads and 5 proposals out."),
      ("maya", "All three clients are on monthly care plans, so recurring revenue is stable."),
      ("daniyal", "We need two more engineers to take on a fourth project."),
      ("shah", "WebflowX needs steady focus too, so let's protect that time."),
      ("elena", "I will draft the Q4 roadmap this week.")],
     ["24 open leads, 5 proposals out", "Three clients on care plans", "Hiring two engineers"],
     ["Q4: two new clients and the Tidewell launch", "Protect WebflowX focus time"],
     [("Elena", "Draft the Q4 roadmap"), ("Zainab", "Open the two engineer roles"), ("Rania", "Prepare the pipeline report")],
     "Q4 goals were set around new clients, the Tidewell launch and protecting product time."),
]
